# Section 2: Data Wrangling

To prepare out data for analysis, we need to perform data wrangling. In this section, we will learn how to clean and transform our data to make it suitable for analysis.

### 🐧 Load the raw dataset

In [2]:
import pandas as pd

# Load raw data
url = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins_raw.csv"
penguins = pd.read_csv(url)

penguins.head()

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN

### 🧼 Step 1: Drop unneeded columns

In [ ]:
# Check columns
penguins.columns

Index(['studyName', 'Sample Number', 'Species', 'Region', 'Island', 'Stage',
       'Individual ID', 'Clutch Completion', 'Date Egg', 'Culmen Length (mm)',
       'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)', 'Sex',
       'Delta 15 N (o/oo)', 'Delta 13 C (o/oo)', 'Comments'],
      dtype='object')

In [ ]:
# Drop columns not in cleaned version (e.g. 'studyName', 'Individual ID', 'Comments')
penguins = penguins.drop(columns=['studyName', 'Sample Number', 'Region', 'Stage',
                                  'Individual ID', 'Clutch Completion', 'Delta 15 N (o/oo)', 'Delta 13 C (o/oo)', 'Comments'])

penguins.head()

,Species,Island,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex
0,Adelie Penguin (Pygoscelis adeliae),Torgersen,2007-11-11,39.1,18.7,181.0,3750.0,MALE
1,Adelie Penguin (Pygoscelis adeliae),Torgersen,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie Penguin (Pygoscelis adeliae),Torgersen,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie Penguin (Pygoscelis adeliae),Torgersen,2007-11-16,NaN,NaN,NaN,NaN,NaN
4,Adelie Penguin (Pygoscelis adeliae),Torgersen,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE



➤ *Why drop columns?*  
Columns irrelevant to the analysis or full of missing/inconsistent data are noise. Drop them early.

### 🏷️ Step 2: Rename columns to match cleaned format
Clean column names to snake_case and consistent naming

In [3]:

penguins = penguins.rename(columns={
    'Species': 'species',
    'Island': 'island',
    'Sex': 'sex',
    'Beak Length (mm)': 'bill_length_mm',
    'Beak Depth (mm)': 'bill_depth_mm',
    'Flipper Length (mm)': 'flipper_length_mm',
    'Body Mass (g)': 'body_mass_g',
    'Date Egg': 'year'
})

penguins.head()

,studyName,Sample Number,species,Region,island,Stage,Individual ID,Clutch Completion,year,Culmen Length (mm),Culmen Depth (mm),flipper_length_mm,body_mass_g,sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN

### 🔁 Step 3: Convert columns to the correct data types and manage the content of the columns

In [4]:
penguins.dtypes

studyName              object
Sample Number           int64
species                object
Region                 object
island                 object
Stage                  object
Individual ID          object
Clutch Completion      object
year                   object
Culmen Length (mm)    float64
Culmen Depth (mm)     float64
flipper_length_mm     float64
body_mass_g           float64
sex                    object
Delta 15 N (o/oo)     float64
Delta 13 C (o/oo)     float64
Comments               object
dtype: object

Change the content of the species column to just the name of the penguing species and make it as a category type.

In [5]:
penguins.species.unique()

array(['Adelie Penguin (Pygoscelis adeliae)',
       'Gentoo penguin (Pygoscelis papua)',
       'Chinstrap penguin (Pygoscelis antarctica)'], dtype=object)

In [6]:
# Just the the first word of the species column
penguins['species'] = penguins['species'].str.split().str[0]

# Convert species to categorical
penguins['species'] = penguins['species'].astype('category')
penguins.head()

,studyName,Sample Number,species,Region,island,Stage,Individual ID,Clutch Completion,year,Culmen Length (mm),Culmen Depth (mm),flipper_length_mm,body_mass_g,sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie,Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie,Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie,Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie,Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie,Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN

Convert the column with the date in the format of the date and keep just the year

In [ ]:
penguins['year'] = pd.to_datetime(penguins['year'])
penguins.head()

In [ ]:
penguins.dtypes

In [ ]:
# Keep only the year part
penguins['year'] = penguins['year'].dt.year
penguins.head()

In [ ]:
penguins['year'].dtypes

In [7]:
# Convert sex to lower case and make it a category type
penguins['sex'] = penguins['sex'].str.lower().astype('category')

# Check types
penguins.dtypes

studyName               object
Sample Number            int64
species               category
Region                  object
island                  object
Stage                   object
Individual ID           object
Clutch Completion       object
year                    object
Culmen Length (mm)     float64
Culmen Depth (mm)      float64
flipper_length_mm      float64
body_mass_g            float64
sex                   category
Delta 15 N (o/oo)      float64
Delta 13 C (o/oo)      float64
Comments                object
dtype: object

➤ *Why care about types?*  
Performance, memory, and avoiding weird bugs when modeling or grouping.

## 📦 GroupBy — Split, Apply, Combine

In [8]:
url_penguins = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv"
penguins = pd.read_csv(url_penguins)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

### Aggregating

In [9]:
penguins['body_mass_g'].mean()

np.float64(4201.754385964912)

In [12]:
species_map = pd.Series([], dtype=float)

for species in penguins['species'].unique():
    species_only = penguins.loc[penguins['species'] == species]
    species_map.loc[species] = species_only['body_mass_g'].mean()

species_map

Adelie       3700.662252
Gentoo       5076.016260
Chinstrap    3733.088235
dtype: float64

### Grouping

In [11]:
# Grouping the 'penguins' DataFrame by 'species' and calculating the mean of 'body_mass_g'
penguins.groupby('species')['body_mass_g'].mean()

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

### ➕ Multiple Columns Aggregated

In [13]:

penguins.groupby('species')[['body_mass_g', 'flipper_length_mm']].mean()

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

### 🧠 Grouping by Multiple Keys

In [14]:
penguins.groupby(['species', 'sex'])['body_mass_g'].mean()

species    sex
Adelie     female    3368.835616
           male      4043.493151
Chinstrap  female    3527.205882
           male      3938.970588
Gentoo     female    4679.741379
           male      5484.836066
Name: body_mass_g, dtype: float64

### 🧮 Use `.agg()` for Multiple Functions

In [15]:

penguins.groupby('species')['body_mass_g'].agg(['mean', 'std', 'count'])

                  mean         std  count
species
Adelie     3700.662252  458.566126    151
Chinstrap  3733.088235  384.335081     68
Gentoo     5076.016260  504.116237    123

### 🧪 Group All Rows, No Column Specified

In [18]:

penguins.groupby('species').mean(numeric_only=True)

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
species,,,,,
Adelie,38.791391,18.346358,189.953642,3700.662252,2008.013158
Chinstrap,48.833824,18.420588,195.823529,3733.088235,2007.970588
Gentoo,47.504878,14.982114,217.186992,5076.016260,2008.080645

### 🧰 Reset Index for Flattened Output

In [20]:
penguins.groupby('species')['body_mass_g'].mean().index #goupby usa come indici i valori utilizzati per fare lo split

Index(['Adelie', 'Chinstrap', 'Gentoo'], dtype='object', name='species')

In [25]:

penguins.groupby('species')['body_mass_g'].mean().reset_index() #alcune funzioni necessitano invece di indici numerici

     species  body_mass_g
0     Adelie  3700.662252
1  Chinstrap  3733.088235
2     Gentoo  5076.016260

## 🧭 Penguin Pivot Tables — From Flat to Insightful

In [22]:
# Import clean data
url_penguins = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv"
penguins = pd.read_csv(url_penguins)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

### 💡 What is a Pivot Table?

```python
pd.pivot_table(df,
index = cols, #  keys to group by for index  
columns = cols2, #  keys to group by for columns
values = cols3, # columns to aggregate
aggfunc = func # aggregation function
)
```

### 📌 Basic Example: Average Body Mass by Species and Sex

Compare **average body mass** per **species**, broken down by **sex**.

In [26]:
pd.pivot_table(
    penguins,
    index='species',
    columns='sex',
    values='body_mass_g',
    aggfunc='mean'
)

sex             female         male
species
Adelie     3368.835616  4043.493151
Chinstrap  3527.205882  3938.970588
Gentoo     4679.741379  5484.836066

### 🔁 Change the Aggregation Function

You're not limited to means. Use `aggfunc` to calculate other statistics.

In [24]:
pd.pivot_table(
    penguins,
    values='flipper_length_mm',
    index='species',
    columns='sex',
    aggfunc='median'
)

sex        female   male
species
Adelie      188.0  193.0
Chinstrap   192.0  200.5
Gentoo      212.0  221.0

### 🔢 Multiple Aggregated Values

You can calculate multiple statistics at once.

In [ ]:
pd.pivot_table(
    penguins,
    values=['body_mass_g', 'flipper_length_mm'],
    index='species',
    columns='sex',
    aggfunc='mean'
)

### 📊 Count Instead of Mean

In [ ]:
pd.pivot_table(
    penguins,
    index='species',
    columns='sex',
    values='body_mass_g',
    aggfunc='count'
)

In [ ]:
pd.pivot_table(
    penguins,
    index='species',
    columns='sex',
    aggfunc='size'
)

### 🧪 Using a `lambda` in a Pivot Table

#### 💡 Goal: Compare the *range* of body mass (max - min) per species and sex

In [ ]:

pd.pivot_table(
    penguins,
    values='body_mass_g',
    index='species',
    columns='sex',
    aggfunc=lambda x: x.max() - x.min()
)